Delete `unused-braces-lint` test
The modified lint correctly provide a span in its suggestion.

```shell
error: unnecessary braces around block return value
  --> /rust/src/test/rustdoc-ui/unused-braces-lint.rs:9:5
   |
LL | /     {
LL | |         {
   | |________^
LL |               use std;
LL |           }
   |  __________^
LL | |     }
   | |_____^
   |
note: the lint level is defined here
  --> /rust/src/test/rustdoc-ui/unused-braces-lint.rs:6:9
   |
LL | #![deny(unused_braces)]
   |         ^^^^^^^^^^^^^
help: remove these braces
   |
LL ~     {
LL |             use std;
LL ~         }
   |
```

It is unclear to which extend https://github.com/rust-lang/rust/issues/70814 is still an issue, as the inital MCVE does not trigger the lint on stable
 either,[rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b6ff31a449c0b73a08daac8ee43b1fa6)